version: '3.8'

services:
  backend:
    image: backend-image
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    image: frontend-image
    container_name: frontend
    ports:
      - "3000:5000"
